language: python
if: branch = master OR tag IS present
python: 3.6
dist: bionic
services:
    - docker

before_script:
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" --password-stdin quay.io
    - pip show rkd

jobs:
    allow_failures:
        env:
            - CAN_FAIL=true

    include:
        -   stage: Run unit tests on Python 3.6
            python: 3.6
            script:
                - pip install -r ./requirements-dev.txt
                - tox -e py36

        -   stage: Run unit tests on Python 3.7
            python: 3.7
            script:
                - pip install -r ./requirements-dev.txt
                - tox -e py37

        -   stage: Run unit tests on Python 3.8
            python: 3.8
            script:
                - pip install -r ./requirements-dev.txt
                - tox -e py38

        -   stage: Release
            python: 3.7
            script: "rkd :release:pypi"

        -   stage: Build recent x86_64 image
            script: "GIT_TAG=${TRAVIS_TAG} rkd :release:docker:x86"

        -   stage: Build recent ARM image
            script: "GIT_TAG=${TRAVIS_TAG} travis_wait 30 rkd :release:docker:arm"
